name: CI using shared actions

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
  release:
    types: [published]
  issue_comment:
    types: [created, edited]

jobs:
  dispatch:
    uses: MagmaWorks/Actions/.github/workflows/dispatch-dotnet.yml@main
    permissions:
      contents: write
      checks: write
      pull-requests: write
