name: CI using shared actions

on:
  issue_comment:
    types: [created, edited]

jobs:
  ci:
    uses: MagmaWorks/Actions/.github/workflows/dotnet-repo.yml@main
    permissions:
      actions: write
      attestations: write
      checks: write
      contents: write
      pull-requests: write
