name: Repo Event Dispatcher

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
  release:
    types: [published]
  issue_comment:
    types: [created, edited]

jobs:
  dispatch:
    uses: MagmaWorks/Actions/.github/workflows/central-dispatch.yml@main
    with:
      codecov: true
      lint: true
      dotnet: '8.0.x'
    permissions:
      contents: write
      checks: write
      pull-requests: write
