name: Repo Event Dispatcher

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
  release:
    types: [published]
  issue_comment:
    types: [created, edited]

jobs:
  dispatch:
    uses: MagmaWorks/Actions/.github/workflows/central-dispatch.yml@main
    with:
      event_name: ${{ github.event_name }}
      ref: ${{ github.ref }}
      head_ref: ${{ github.head_ref || '' }}
      comment_body: ${{ github.event.comment.body || '' }}
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
